grails-app/controllers/docker/registry/web/AccountController.groovy
package docker.registry.web

import docker.registry.Event
import docker.registry.User
import grails.transaction.Transactional

class AccountController {

  def passwordEncoder
  def springSecurityService

  def index() {
    def user = springSecurityService.currentUser
    def events = Event.findAllByUsername(user.username, [max: 20, order: 'desc', sort: 'id'])
    [user: user, events: events]
  }


  @Transactional
  def updatePassword() {
    String oldPassword = params.oldPassword
    String newPassword = params.newPassword
    String newPasswordRepeat = params.newPasswordRepeat
    User user = springSecurityService.currentUser
    //validates raw password against hashed
    if (!passwordEncoder.isPasswordValid(user.password, oldPassword, null)) {
      flash.message = 'password.incorrect'
      log.warn flash.message
      redirect(action: 'changePassword')
    } else {
      if (newPassword.length() == 0) {
        flash.message = 'password.empty'
        log.warn flash.message
        redirect(action: 'changePassword')
      } else if (newPassword != newPasswordRepeat) {
        flash.message = 'password.notmatch'
        log.warn flash.message
        redirect(action: 'changePassword')
      } else {
        log.warn "Updating password for user=${user}"
        user.password = newPassword
        flash.message = 'password.updated'
        redirect(action: 'index')
      }
    }
  }

  def changePassword() {
    def user = springSecurityService.currentUser
    [user: user]
  }
}

grails-app/controllers/docker/registry/web/EventController.groovy
package docker.registry.web

import docker.registry.Event

class EventController {

  def index() {
    def total = Event.count()
    def list = Event.list max: 20, offset: params.offset, sort: 'id', order: 'desc'
    [list: list, total: total]
  }
}

grails-app/controllers/docker/registry/web/RepositoryController.groovy
package docker.registry.web

import groovy.json.JsonSlurper
import org.springframework.beans.factory.annotation.Value

class RepositoryController {
  @Value('${registry.readonly}')
  boolean readonly
  int recordsPerPage = 100

  @Value('${registry.name}')
  String registryName

  def restService
  def authService

  //{"Type":"registry","Name":"catalog","Action":"*"}
  def index() {
    def repoCount = []
    boolean pagination = false
    def next = null
    boolean hasNext = false
    def message
    def url = "_catalog?n=${recordsPerPage}"
    try {
      if (params.start) {
        url += "&last=${params.start}"
      }
      def restResponse = restService.get(url, restService.generateAccess('catalog', '*', 'registry'))
      if (!restResponse.statusCode.'2xxSuccessful') {
        def statusCode = restResponse.statusCode
        log.warn "URI: '$url' responseCode: ${statusCode}"
        message = "status=${statusCode} ${statusCode.name()} ${restResponse.text}"

      }
      hasNext = restResponse.headers.getFirst('Link') != null
      pagination = hasNext || params.prev != null
      def repos = restResponse.json.repositories
      next = repos ? repos.last() : null

      repoCount = repos.collect { name ->
        def tagsCount = getTagList(name).size()
        [name: name, tags: tagsCount]
      }
    } catch (e) {
      log.error "Can't access registry: $url", e
      message = e.message
    }
    [repos: repoCount, pagination: pagination, next: next, prev: params.start, hasNext: hasNext, registryName: registryName, message: message]
  }

  def tags() {
    String name = params.id.decodeURL()
    def tags = getTags(name)
    if (!tags.count { it.exists }) {
      log.warn "Repo name: ${name} is empty, redirecting to home page"
      redirect action: 'index'
    } else {
      def deletePermitted = authService.checkLocalDeletePermissions(name)
      [tags: tags, readonly: readonly || !deletePermitted, registryName: registryName]
    }
  }


  private def getTags(name) {
    def tags = getTagList(name).findAll { it }.collect { tag ->
      def manifest = restService.get("${name}/manifests/${tag}", restService.generateAccess(name))
      def exists = manifest.statusCode.'2xxSuccessful'
      def topLayer
      def size = 0
      def layers
      if (exists) {
        topLayer = new JsonSlurper().parseText(manifest.json.history.first().v1Compatibility)
        layers = getLayers(name, tag)
        size = layers.collect { it.value }.sum()
      }

      def createdStr = topLayer?.created
      def createdDate = DateConverter.convert(createdStr)
      long unixTime = createdDate?.time ?: 0

      [name: tag, count: layers?.size(), size: size, exists: exists, id: topLayer?.id?.substring(0, 11), created: createdDate, createdStr: createdStr, unixTime: unixTime]
    }
    tags
  }

  private def getLayers(String name, String tag) {
    def json = restService.get("${name}/manifests/${tag}", restService.generateAccess(name), true).json

    if (json.schemaVersion == 2)
      return json.layers.collectEntries { [it.digest, it.size as BigInteger] }
    else {
      //fallback to manifest schema v1
      def history = json.history.v1Compatibility.collect { jsonValue ->
        new JsonSlurper().parseText(jsonValue)
      }

      def digests = json.fsLayers.collect { it.blobSum }
      history.eachWithIndex { entry, i ->
        entry.digest = digests[i]
        entry.size = entry.Size ?: 0
      }

      return history.collectEntries {
        [it.digest, it.size as BigInteger]
      }
    }
  }

  private List getTagList(name) {
    restService.get("${name}/tags/list", restService.generateAccess(name)).json?.tags ?: []
  }

  def tag() {
    def name = params.id.decodeURL()
    def tag = params.name
    def res = restService.get("${name}/manifests/${tag}", restService.generateAccess(name)).json
    def history = res.history.v1Compatibility.collect { jsonValue ->
      def json = new JsonSlurper().parseText(jsonValue)
      [id: json.id.substring(0, 11), cmd: (json.container_config.Cmd?.last() ?: '').replaceAll('&&', '&&\n')]
    }

    def blobs = res.fsLayers.collect { it.blobSum }
    def layers = getLayers(name, tag)
    history.eachWithIndex { entry, i ->
      def digest = blobs[i]
      entry.size = layers[digest] ?: 0
    }

    [history: history, totalSize: history.sum { it.size }, registryName: registryName]
  }

  def delete() {
    String name = params.id.decodeURL()
    def tag = params.name
    if (!readonly) {
      def manifest = restService.get("${name}/manifests/${tag}", restService.generateAccess(name, 'pull'), true)
      def digest = manifest.responseEntity.headers.getFirst('Docker-Content-Digest')
      log.info "Manifest digest: $digest"
      /*
    def blobSums = manifest.json.fsLayers?.blobSum
    blobSums.each { digest ->
      log.info "Deleting blob: ${digest}"
      restService.delete("${name}/blobs/${digest}")
    }
    */
      if (authService.checkLocalDeletePermissions(name)) {
        log.info "Deleting manifest"
        def result = restService.delete("${name}/manifests/${digest}", restService.generateAccess(name, '*'))
        if (!result.deleted) {
          def text = ''
          try {
            boolean unsupported = result.response.json.errors[0].code == 'UNSUPPORTED'
            text = unsupported ? "Deletion disabled in registry, <a href='https://docs.docker.com/registry/configuration/#delete'>more info</a>." : result.text
          } catch (e) {
            log.warn "Error deleting", e
            text = result.text
          }
          flash.message = "Error deleting ${name}:${tag}: ${text}"
        }
      } else {
        log.warn 'Delete not allowed!'
        flash.message = "Delete not allowed!"
      }
    } else {
      log.warn 'Readonly mode!'
      flash.message = "Readonly mode!"
    }
    flash.deleteAction = true
    redirect action: 'tags', id: params.id
  }
}

grails-app/controllers/docker/registry/web/StatusController.groovy
package docker.registry.web

class StatusController {
  def grailsApplication
  def tokenService
  def configService

  def index() {
    def meta = grailsApplication.metadata
    log.info "Starting registry-web ver. ${meta['app.version']}-${meta['app.commit']}"
    def version = meta['app.version']
    def fullHash = meta['app.commit']
    def hash = fullHash ? fullHash[0..6] : 'dev'
    [version: "${version}-${hash}", keyDigest: tokenService.keyDigest, configPath: grailsApplication.config.yaml.path,
     config : configService.configMap()]
  }
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Web Registry - <g:layoutTitle/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
    <asset:stylesheet src="application.css"/>
    <asset:javascript src="application.js"/>
    <asset:deferredScripts/>
    <g:layoutHead/>
</head>

<body>
<!-- navbar -->

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>  <g:link class="navbar-brand" controller="repository" action="index">Web Registry</g:link>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">

                <sec:ifAnyGranted roles="UI_ADMIN">
                    <li>
                        <g:link controller="user">Users</g:link>
                    </li>
                    <li>
                        <g:link controller="role">Roles</g:link>
                    </li></sec:ifAnyGranted>
                <sec:ifLoggedIn>
                    <li>
                        <g:link controller="event">Events</g:link>
                    </li>
                    <li>
                        <g:link controller="status">Status</g:link>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"><strong><sec:username/><span class="caret"></span></strong></a>
                        <ul class="dropdown-menu">
                            <li><g:link controller="account" action="index">My Account</g:link></li>
                            <li role="separator" class="divider"></li>
                            <li><g:link controller="logout" action="index">Log Out</g:link></li>
                        </ul>
                    </li>
                </sec:ifLoggedIn>
            </ul>

        </div>
    </div>
</nav>


<div class="container">
    <g:layoutBody/>
</div>
</body>
</html>